<?php


/**
 *  Implementation of hook_is_mobile_device() provide by Mobile Tools module
 *
 */  
function mt_browscap_is_mobile_device() {
  $info = browscap_get_browser();
 // detect device type 
 if ($info['ismobiledevice']) {
    $type = 'mobile';
 } else {
    $type = 'desktop';
 }
 
 $groups = mt_browscap_device_groups();
 $group = '';
 if (in_array($info['browser'], $groups)) {
  $group = $info['browser'];
 }
 return array('type'=> $type, 'group' => $group);
}

/**
 *  Implementation of hook_device_groups() as provided by Mobile Tools module 
 */ 
function mt_browscap_device_groups() {
  return array('iPhone', 'iPod', 'Android', 'Opera Mini', 'BlackBerry');
}

/** 
 *
 */  